SELECT 
    MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') as DATE_OF_BIRTH 
FROM
    MEMBER_PROFILE
WHERE 
    # 두 함수 모두 03, 3, '03', '3'을 넣어도 정답 처리됨
    # DATE_FORMAT(DATE_OF_BIRTH, '%m') = 03
    MONTH(DATE_OF_BIRTH) = '03'
AND
    TLNO IS NOT NULL
AND 
    GENDER = 'W'
ORDER BY
    MEMBER_ID