-- 버전 1 : BIT_OR
WITH FRONTEND AS (
    SELECT BIT_OR(CODE) AS MASK 
    FROM SKILLCODES
    WHERE CATEGORY = 'FRONT END'
)

SELECT 
    ID, EMAIL, FIRST_NAME, LAST_NAME 
FROM 
    DEVELOPERS D 
JOIN 
    FRONTEND F 
ON D.SKILL_CODE & F.MASK 
ORDER BY 
    ID
    
    
-- 버전 2 : DISTINCT
WITH FRONTEND AS (
    SELECT CODE  
    FROM SKILLCODES
    WHERE CATEGORY = 'FRONT END'
)

SELECT 
    DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME 
FROM 
    DEVELOPERS D 
JOIN 
    FRONTEND F 
ON D.SKILL_CODE & F.CODE 
ORDER BY 
    ID