SELECT a.ID, IFNULL(CHILD_COUNT, 0) as CHILD_COUNT
FROM ECOLI_DATA a
LEFT JOIN 
    (SELECT PARENT_ID, COUNT(*) as CHILD_COUNT 
     FROM ECOLI_DATA 
     WHERE PARENT_ID IS NOT NULL 
     GROUP BY PARENT_ID) as b
ON a.ID = b.PARENT_ID
ORDER BY a.ID