WITH INTACT_UPON_INTAKE AS (
    SELECT ANIMAL_ID 
    FROM ANIMAL_INS
    WHERE LEFT(SEX_UPON_INTAKE, 6) = 'INTACT'
)

SELECT 
    O.ANIMAL_ID, 
    O.ANIMAL_TYPE, 
    O.NAME 
FROM 
    ANIMAL_OUTS O
JOIN 
    INTACT_UPON_INTAKE I
ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE LEFT(O.SEX_UPON_OUTCOME, 6) != 'INTACT'
ORDER BY
    O.ANIMAL_ID