SELECT
    DATE_FORMAT(SALES_DATE, "%Y-%m-%d"), PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE N 
WHERE DATE_FORMAT(SALES_DATE, "%Y-%m") = '2022-03'

UNION

SELECT
    DATE_FORMAT(SALES_DATE, "%Y-%m-%d"), PRODUCT_ID, null, SALES_AMOUNT
FROM OFFLINE_SALE F
WHERE DATE_FORMAT(SALES_DATE, "%Y-%m") = '2022-03'

ORDER BY 1, 2, 3