-- 버전 1
SELECT F.FLAVOR
FROM FIRST_HALF F 
LEFT JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) as TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
) J
ON F.FLAVOR = J.FLAVOR
GROUP BY F.FLAVOR
ORDER BY SUM(F.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) DESC
LIMIT 3

-- 버전 2
SELECT F.FLAVOR
    FROM FIRST_HALF F 
    LEFT JOIN JULY J
    ON F.FLAVOR = J.FLAVOR
GROUP BY F.FLAVOR
ORDER BY F.TOTAL_ORDER + SUM(J.TOTAL_ORDER) DESC
LIMIT 3