-- 버전 1
SELECT 
    C.CAR_ID,
    P.CAR_TYPE,
    FLOOR(C.DAILY_FEE * (100 - P.DISCOUNT_RATE) / 100 * 30) AS FEE
FROM
    CAR_RENTAL_COMPANY_CAR C
JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON C.CAR_TYPE = P.CAR_TYPE
WHERE
    C.CAR_TYPE IN ('세단', 'SUV')
    AND P.DURATION_TYPE = '30일 이상'
    AND FLOOR(C.DAILY_FEE * (100 - P.DISCOUNT_RATE) / 100 * 30) BETWEEN 500000 AND 1999999
    AND C.CAR_ID NOT IN (
        SELECT 1
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        WHERE H.CAR_ID = C.CAR_ID
          AND H.START_DATE <= '2022-11-30'
          AND H.END_DATE >= '2022-11-01' 
    )
ORDER BY
    FEE DESC,
    P.CAR_TYPE ASC,
    C.CAR_ID DESC;
    
-- 버전 2
SELECT 
    C.CAR_ID, 
    P.CAR_TYPE, 
    FLOOR(C.DAILY_FEE * (100 - P.DISCOUNT_RATE) / 100 * 30) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR C 
JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
ON C.CAR_TYPE = P.CAR_TYPE
WHERE 
    C.CAR_ID NOT IN (
        SELECT CAR_ID 
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
    )
    AND C.CAR_TYPE IN ('SUV', '세단')
    AND P.DURATION_TYPE = '30일 이상'
    AND FLOOR(C.DAILY_FEE * (100 - P.DISCOUNT_RATE) / 100 * 30) BETWEEN 500000 AND 2000000
ORDER BY 
    FEE DESC,
    P.CAR_TYPE,
    C.CAR_ID DESC;