WITH USERS AS (
    SELECT 
        COUNT(USER_ID) AS USER_COUNT 
    FROM 
        USER_INFO 
    WHERE
        SUBSTR(JOINED, 1, 4) = '2021'
)
    
SELECT 
    YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, 
    COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS, 
    ROUND(COUNT(DISTINCT O.USER_ID) / USER_COUNT, 1) AS PUCHASED_RATIO
FROM 
    ONLINE_SALE O 
JOIN
    USER_INFO U 
ON 
    O.USER_ID = U.USER_ID 
CROSS JOIN 
    USERS US 
WHERE
    SUBSTR(U.JOINED, 1, 4) = '2021'
GROUP BY 
    YEAR, 
    MONTH 
ORDER BY 
    YEAR, 
    MONTH  